### ISSUE TITLE
Top level css selector

### ISSUE THREAD

**Issue by zagortenay333** [lestcape/Color-Chooser#1]
Awesome applet!

Could you add a top-level selector to this applet? Just like the weather and x-center applet. It would allow me to override the `popup-menu` selector and target certain elements like the vertical slider:

![screenshot from 2015-07-13 12 07 38](https://cloud.githubusercontent.com/assets/11144630/8647410/0683cc5a-2958-11e5-9ec1-1094bef4394c.png)

**Comment by lestcape** [comment]
Yes, i can. i also agree with you and i open a feature request to be consider create a general way to resolve problem like this automatically in cinnamon. Anyway, i think, I can continue making patches with the  selectors, waiting for a more general solution. https://github.com/linuxmint/Cinnamon/issues/4428

**Comment by zagortenay333** [comment]
Interesting!

**Comment by lestcape** [comment]
Added an option to override the Top level scale css selector: https://github.com/lestcape/Color-Chooser/commit/bae95d7047f04d10a82940890b1f036fc3ed95c0

Now this is the heritage:
1-top: popup-slider-menu-item
2-scale: popup-scale-menu-item
3-scale-color: color-scale

So, you can override the standar selector of "popup-slider-menu-item" using "popup-scale-menu-item" or as an option when scale are not used as a separate item and is used with a color to scale, you can use the selector "color-scale", how i don't used the scale as a separate item, both will have the same effect.

**Comment by zagortenay333** [comment]
Nice! I haven't been very active on cinnamon for a while. Added styles for this applet for my Tertia theme: https://github.com/zagortenay333/ciliora-tertia-cinnamon/commit/d39095cfecdcc1f7166a70bf9b132b356e0bf5b4

Will add for the others eventually too.

**Comment by lestcape** [comment]
ok, thanks.
