### ISSUE TITLE
The color picker is often wrong

### ISSUE THREAD

**Issue by robrobinbin** [lestcape/Color-Chooser#3]
The cursor (after I choose the colour picker and before I click to select a colour) changes from light to dark when I move it around as if there are dark lines (or other figures) all over my screen, even if I'm moving over a white surface. And indeed when I click I get colours that are lighter or darker than the expected colour. When click on the right spots on a completely white background I can get all kind of greys and even black.

**Comment by lestcape** [comment]
Yes, that is right, there are a problem. The GdkWindows in Cinnamon are not fully supported. So, to get the real color you will need to compare the circle inside the "mouse" to the color that you want select. The little circle is a hint of what color you have. I don't know how i can improve that, as i'm not who select the color, is a library that not run properly inside cinnamon.

But this could not be your problem, the desktop not have really a linear color. When yo convert a print screen to a bitmap, you will get some different color in an area that you suppose have only one color. There are a desktop composition and the finally output is not the primary one.

**Comment by lestcape** [comment]
I will try to disappear the "mouse" and see if this is the cause. Cloud be an slow color estimation, so the information of the screen cloud take in consideration the "mouse" and with a delay time, probably you will get a pixel that it's inside the mouse and not inside the image.

**Comment by lestcape** [comment]
https://github.com/lestcape/Color-Chooser/commit/62f8f68912094bd7516a722bf007df4e299cd77a
